databases:
  - name: yoon-db
    databaseName: yoon
    user: yoon_user
    plan: free

services:
  - type: redis
    name: yoon-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction

  - type: web
    name: yoon-web
    env: docker
    plan: free
    dockerCommand: "/usr/local/bin/start.sh"
    envVars:
      - key: APP_NAME
        value: Yoon
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: yoon-db
          property: connectionString
      - key: APP_KEY
        value: "base64:bazi4To+VqmbaIj905PSYnID1ZruDP/+kxv7dDZCFhY="
      - key: REVERB_APP_ID
        value: "452299"
      - key: REVERB_APP_KEY
        value: "4qkyonks9nnrsiz6qnck"
      - key: REVERB_APP_SECRET
        value: "gdedjqiwhtskzgiuuovs"
      - key: VITE_REVERB_APP_KEY
        value: "4qkyonks9nnrsiz6qnck"
      - key: VITE_REVERB_PORT
        value: "443"
      - key: VITE_REVERB_SCHEME
        value: "https"
      - key: REDIS_URL
        fromService:
          type: redis
          name: yoon-redis
          property: connectionString
      - key: CACHE_STORE
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_CONNECTION
        value: reverb

  - type: web
    name: yoon-reverb
    env: docker
    plan: free
    dockerCommand: "php artisan reverb:start --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: yoon-db
          property: connectionString
      - key: REVERB_APP_ID
        value: "452299"
      - key: REVERB_APP_KEY
        value: "4qkyonks9nnrsiz6qnck"
      - key: REVERB_APP_SECRET
        value: "gdedjqiwhtskzgiuuovs"
      - key: REDIS_URL
        fromService:
          type: redis
          name: yoon-redis
          property: connectionString
